program:
  host: "0.0.0.0"
  port: 8080
  alive_time: 60
  log_level: "INFO"

Local-Models:
  jina-code-embeddings:
    aliases:
      - "jina-code-embeddings"
    mode: "Embedding"
    port: 10001
    auto_start: false
    CPU:
      required_devices:
        - "CPU"
      script_path: "Model_startup_script/jina-code-embeddings.sh"
      memory_mb:
        CPU: 2048
